name: linux

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SETUP: ['/cvmfs/sw.hsf.org/key4hep/setup.sh', '/cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh']
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - name: Start container
      run: |
        docker run \
          -it --name k4_CI \
          -v ${{ github.workspace }}:/Package \
          -v /cvmfs:/cvmfs:shared \
          -d ghcr.io/aidasoft/centos7:latest /bin/bash
    - name: Compile
      run: |
        docker exec k4_CI /bin/bash -c 'source ${{ matrix.SETUP }};
          cd Package;
          mkdir build install; cd build;
          cmake -G Ninja -D CMAKE_INSTALL_PREFIX=$PWD/../install -D CMAKE_BUILD_TYPE=RelWithDebInfo ..;
          ninja install;
        '
